### ISSUE TITLE
Numpy random can cause bugs

### ISSUE THREAD

**Issue by gijskoning** [INFLUENCEorg/influence-aware-memory#4]
Hey Miguel,
I recently came upon this Twitter post from Karpathy saying that you should be careful when using the Numpy random generator in combination with Pytorch. Since when using multiple workers it can happen that workers still share the same seed number when it is generated from Numpy which is not wanted. This might be relevant in this class and maybe other environments in this repo. More information is found here: https://twitter.com/karpathy/status/1381121537164513288?s=20
https://github.com/INFLUENCEorg/influence-aware-memory/blob/c3acd7c4202d2b4da5cf2b3d2057b679e3c9fb41/environments/warehouse/warehouse.py#L145

**Comment by miguelsuau** [comment]
Hi Gijs,
Thanks for pointing this out. I also saw that tweet and wondered the same thing but I think it's only a problem if you use Pytorch's built-in multiprocessing. I remember I ran some tests a while ago to check that the environment's starting state for each worker was indeed different. Wouldn't be a bad idea to double-check though.

**Comment by gijskoning** [comment]
Ah great that it is hopefully not an issue in this repo :). Good to know that it is only happening in specific cases
